### ISSUE TITLE
Suggest to name this repo as "DeBank.com user feedbacks" : ), my feedbacks 

### ISSUE THREAD

**Issue by zhangzhongnan928** [DeBankDeFi/Issues#1]
1. Add an option to connect web3 wallet to load wallet address directly 
![IMG_2398](https://user-images.githubusercontent.com/33795543/78217722-55545600-7508-11ea-8849-f40d7ef3c7c6.PNG)

2. Display reverse record of ENS
![IMG_2399](https://user-images.githubusercontent.com/33795543/78217943-b7ad5680-7508-11ea-91e9-7b9191bf5aeb.PNG)
![IMG_2400](https://user-images.githubusercontent.com/33795543/78218060-e5929b00-7508-11ea-8f10-ed266bf89de2.jpg)

3. Add more features to the mobile version : )

I love your product, nice work.
P.S. welcome to fork an AlphaWallet([iOS](https://github.com/AlphaWallet/alpha-wallet-ios) and [Andriod](https://github.com/AlphaWallet/alpha-wallet-android)) as DeBank mobile app.

**Comment by wooparadog** [comment]
> 1. Add an option to connect web3 wallet to load wallet address directly

It's well underway.

> 2. Display reverse record of ENS

It's benn added.

> 3. Add more features to the mobile version : )

We've just added  https://debank.com/rates :D
